### ISSUE TITLE
Superset of Unicode?

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-glossary#14]
https://www.w3.org/TR/i18n-glossary/#def_universal_character_set

> Other [character sets](https://www.w3.org/TR/i18n-glossary/#def_character_set) are subsets of Unicode.

I wonder if that's really the case since obviously there are exceptions like Emacs:

* https://git.savannah.gnu.org/cgit/emacs.git/tree/etc/NEWS.23#n837
* https://www.gnu.org/software/emacs/manual/html_node/emacs/International-Chars.html

**Comment by himorin** [comment]
might be better to include elisp one also? (extended for backward compatibility,,,) 
https://www.gnu.org/software/emacs/manual/html_node/elisp/Text-Representations.html

**Comment by aphillips** [comment]
It's really true that other character sets are subsets of Unicode.

The emacs situation is that they have a larger *code space* than Unicode (which they partially get by using the original UTF-8 design that allowed up to six bytes), but the additional code space really isn't useful in any practical sense. It's also good to ignore such claims, given that we don't really want people thinking there is some other encoding source of truth. There aren't character sets with *more* encoded characters than Unicode.

What is the proposal here?

**Comment by xfq** [comment]
Fair enough. Closing this issue.
