### ISSUE TITLE
Define more terms?

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-glossary#17]
There are some terms we can consider defining:

## Unicode Normalization

The term is used in many specifications and it might be useful to have a definition.

## Compatibility Characters

Defining this term is useful for understanding compatibility decomposition.

## Ruby

A brief explanation should be fine. More info can be found in the following links:

* [HTML](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-ruby-element)
* [CSS](https://www.w3.org/TR/css-ruby-1/)
* [CLReq](https://www.w3.org/TR/clreq/#interlinear_annotations)
* [JLReq](https://www.w3.org/TR/jlreq/#term.ruby)

## Script and writing system

I always feel that these two terms are not easy to understand. It would be nice if there is a clear definition.

## Composite messages

As in https://www.w3.org/International/articles/composite-messages/index

## Surrogate

It is useful for understanding some UTF-16-related issues.

**Unicode scalar value** can be defined too.

Ref: https://infra.spec.whatwg.org/#surrogate

## CJK (or CJKV?)

This is also a term that appears in many specifications.

## Combining character

The term is used in many specifications, such as:

* [MathML Core](https://w3c.github.io/mathml-core/#combining-character-equivalences)
* [UI Events](https://w3c.github.io/uievents/#keys-dead)

## European numerals

The term is used in a few lreq documents.

## halfwidth/fullwidth

It is used in {c,j,k}lreq.

**Comment by r12a** [comment]
These should all be covered by the PR at https://github.com/w3c/i18n-glossary/pull/26
