### ISSUE TITLE
Items from lreq that could be added to Glossary

### ISSUE THREAD

**Issue by r12a** [w3c/i18n-glossary#22]
First step is to identify which items should be moved to the i18n glossary.  I'm putting check marks against those i'd recommend.  Once we have discussed the choice, then we need to add those definitions with check marks to the glossary.

These terms are used in the Thai and Gurmukhi lreq docs, but are not in https://w3c.github.io/i18n-glossary/
Terms with *** are ones i invented for lack of suitable alternatives.

- [x] Abugida
- [x] Vowel sign
- [ ] Onset
- [x] Circumgraph ***
- [x] Conjunct
- [x] Inherent vowel
- [x] Pre-base vowel ***
- [x] Independent vowel
- [x] Standalone vowel ***
- [x] Composite vowel ***
- [ ] Vocalic
- [x] Orthographic syllable
- [x] Alphabet

The following terms are in https://r12a.github.io/scripts/glossary/ but not in https://w3c.github.io/i18n-glossary/ (and the terms above are not included in this list).

- [ ] Brahmi phonetic matrix
- [ ] Checked
- [ ] Coda (syllable)
- [x] Combining character
- [x] Combining character sequence (CCS)
- [x] Consonant cluster
- [ ] Contour tone language
- [x] Cursive
- [x] Decomposed text
- [x] Dependent vowel
- [x] Featural syllabary
- [x] Hyphenation
- [x] Ideograph
- [x] Ijam
- [ ] Invisible stacker
- [x] Justification
- [x] Letter spacing
- [ ] Mater lectionis
- [ ] Moraic syllabary
- [x] Normalisation
- [x] Normalisation form C (NFC)
- [x] Normalisation form D (NFD)
- [ ] Nucleus (syllable)
- [x] Precomposed text / characters
- [ ] Pure killer
- [ ] Register tone language
- [ ] Rhyme (syllable)
- [x] Shaping
- [x] Spacing mark
- [x] Syllabary
- [x] Syllable structure
- [ ] Tone
- [x] Transliteration
- [x] Transcription
- [x] Typographic unit
- [ ] Unchecked
- [x] Virama
- [x] Word boundary

**Comment by aphillips** [comment]
I would probably define all four normalization forms, not just NFC and NFD.

(as chair) Added to our agenda for 2023-03-02.

**Comment by r12a** [comment]
Add Spillover and other bidi terms we use
Check for correspondences with Infra glossary

**Comment by r12a** [comment]
First draft at https://github.com/w3c/i18n-glossary/pull/26 covers the terms in the first comment above. More to come.

**Comment by r12a** [comment]
@aphillips i'm not seeing a pre-made definition for 'spillover'.  Care to provide one?
What other bidi terms did you have in mind?

**Comment by r12a** [comment]
Hopefully, this is covered by https://github.com/w3c/i18n-glossary/pull/26. If not, please raise another PR.  Known exceptions still outstanding include NFKC, NFKD, and 'spillover'.
