### ISSUE TITLE
Automatic pluralization

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-glossary#25]
We have definitions like `<dfn data-lt="code unit|code units">` in a lot of places, but as far as I know we don't need to add the plural form, since [ReSpec](https://respec.org/docs/#automatic-pluralization) and [Bikeshed](https://speced.github.io/bikeshed/#conjugating) handle pluralization automatically.

**Comment by r12a** [comment]
I think i may have fixed all of these in https://github.com/w3c/i18n-glossary/pull/26. If not, please raise another PR.

**Comment by xfq** [comment]
I found two more, and originally wanted to raise a PR, but I made a mistake and committed directly: https://github.com/w3c/i18n-glossary/commit/b2f933101bde39c059b80696e56f6bb4997f94fb

**Comment by r12a** [comment]
The code unit entry also has an id which should be removed.
