### ISSUE TITLE
Restore acknowledgements?

### ISSUE THREAD

**Issue by aphillips** [w3c/i18n-glossary#31]
The acknowledgements section of the glossary is commented out. Should it be removed or restored?

**Comment by r12a** [comment]
We should remove it if we don't come up with anyone to acknowledge - it's just commented out boilerplate text for now.  The names are not relevant to this glossary.

**Comment by aphillips** [comment]
Do you know where it came from? If it's a holdover from elsewhere, we should just remove it.

**Comment by xfq** [comment]
Looking at the names, I thought it came from string-meta, so I took a look and it confirmed my suspicions: https://github.com/w3c/string-meta/blob/3ed0424c4b2a529b44df0e2cd33e72eaac0ad86d/index.html#L1345

**Comment by xfq** [comment]
The names have been removed in https://github.com/w3c/i18n-glossary/pull/27/files

**Comment by aphillips** [comment]
I removed the whole thing in #34. We can restore it if we need it in the future.

**Comment by aphillips** [comment]
PS> Thanks @xfq for finding the origin!!!
