### ISSUE TITLE
Add bicameral and unicameral?

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-glossary#37]
These terms are used in places like [css-fonts](https://www.w3.org/TR/css-fonts-5/#font-size-adjust-prop), [css-inline](https://www.w3.org/TR/css-inline-3/#hanging-baseline), and [hlreq](https://www.w3.org/International/hlreq/#h_script_overview).

**Comment by r12a** [comment]
I'm not sure these are technical terms, rather than ordinary English words.  They may be on the cusp, but i don't think there's any subtle meanings that will be unclear.

**Comment by xfq** [comment]
I can only find the meaning related to legislature when I look them up in the dictionaries:

* [Merriam-Webster](https://www.merriam-webster.com/dictionary/bicameral)
* [Dictionary.com](https://www.dictionary.com/browse/bicameral)
* [Cambridge Dictionary](https://dictionary.cambridge.org/dictionary/english/bicameral)

Unicode also explains the words in [TUS](https://www.unicode.org/versions/Unicode15.0.0/ch05.pdf#G21180) and their [glossary](https://unicode.org/glossary/#bicameral).
