### ISSUE TITLE
Legacy character encodings

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-glossary#60]
https://www.w3.org/TR/i18n-glossary/#dfn-legacy-character-encodings

> Legacy character encodings. Character encoding forms that do not encode the full repertoire of characters in the Unicode character set.

It seems that UTF-32 and GB 18030 don't count as legacy character encodings according to this definition. Is it intentional?

**Comment by aphillips** [comment]
UTF-32 certainly is not a legacy character encoding, since it is, in fact, a Unicode encoding defined by Unicode.

GB18030 is an interesting case, since it does encode the full repertoire but is not a Unicode encoding defined by Unicode. I think I'm fine with the ambiguity in that case?

**Comment by xfq** [comment]
OK. Closing this. Thank you!
