### ISSUE TITLE
Revert export of UTF-8

### ISSUE THREAD

**Issue by annevk** [w3c/i18n-glossary#66]
Because of this every standard referencing the Encoding Standard now has a conflict.

It doesn't seem like a good idea to export UTF-16 either.

See also #28 for issues this document has caused in the past. If this keeps happening we might have to remove this document from the index entirely as this is rather disruptive for everyone else. E.g., the URL Standard no longer builds now.

**Comment by aphillips** [comment]
Thanks for this report. I will fix this today.

I will also include documentation to ensure that this doesn't recur.

**Comment by annevk** [comment]
Thank you!

**Comment by aphillips** [comment]
> See also https://github.com/w3c/i18n-glossary/issues/28 for issues this document has caused in the past. If this keeps happening we might have to remove this document from the index entirely as this is rather disruptive for everyone else.

We (I18N) have the problem that not everyone is using Encoding or Infra at W3C. #28 is about several things, one of which is ensuring that we say the same thing and another of which (as here) is to avoid stepping on each other's toes. That said, our glossary is extremely useful to us as a way of helping spec writers across W3C avoid creating and maintaining separate local definitions. Removing it from the index would break a lot of people too.

**Comment by annevk** [comment]
It seems at this point specifications that depend on strings in some manner would need very strong justification not to build on top of Encoding/Infra.

**Comment by xfq** [comment]
Thinking about this off the top of my head, [RDF](https://www.w3.org/TR/rdf12-concepts/#rdf-strings) is an example of strings not based on 16-bit code units.

**Comment by annevk** [comment]
@xfq they could use https://infra.spec.whatwg.org/#scalar-value-string.

**Comment by aphillips** [comment]
@annevk while this sounds reasonable, I think our experience is that some XML, RDF, and related specs find this difficult to adopt. This isn't a good place to discuss and it deserves "higher bandwidth" conversation. I created an issue in our activity tracker so we can include it in the February 22nd agenda.
