### ISSUE TITLE
Definition of cursive scripts

### ISSUE THREAD

**Issue by xfq** [w3c/i18n-glossary#70]
https://w3c.github.io/i18n-glossary/#dfn-cursive

> Cursive scripts include Adlam, Arabic, Hanifi Rohingya, Mongolian, N'Ko, and Syriac.

The Phagspa script seems to be a cursive script too. Maybe we can limit the definition to something like:

> Cursive scripts in use today include Adlam, Arabic, Hanifi Rohingya, Mongolian, N'Ko, and Syriac.

**Comment by r12a** [comment]
In fact

**Comment by aphillips** [comment]
The existing text doesn't claim to be exhaustive. Adding "in use today" saves use from having to mention Phagspa, but then I'm not sure we needed to mention it?

**Comment by aphillips** [comment]
no changes per 2024-03-14 call, list is not exhaustive.
